<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp3.1;net6.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>HalfMaid.Img.Fonts</Title>
    <LangVersion>10.0</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Version>0.1.0</Version>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Clean Mono-15.png" />
    <EmbeddedResource Include="Resources\Clean-15.png" />
    <EmbeddedResource Include="Resources\Pixelly Bold-9.png" />
    <EmbeddedResource Include="Resources\Pixelly-9.png" />
    <EmbeddedResource Include="Resources\Tiny-6.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HalfMaid.Img\HalfMaid.Img.csproj" />
  </ItemGroup>

</Project>
