<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netcoreapp3.1;net6.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>HalfMaid.Img.OpenGL</Title>
    <LangVersion>10.0</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Version>0.1.0</Version>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK.Graphics" Version="[4.1.0,)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HalfMaid.Img\HalfMaid.Img.csproj" />
  </ItemGroup>

</Project>
